/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cand.app;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeIn;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.security.OAuthFlows;
import io.swagger.v3.oas.annotations.security.SecurityScheme;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SecurityScheme(name = "javainuseapi", scheme = "basic", type = SecuritySchemeType.HTTP, in = SecuritySchemeIn.HEADER)
@OpenAPIDefinition(info = @Info(title = "Customer API", version = "2.0", description = "Customer Information"))
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
        System.out.println("Using Spring-Doc-OpenAPI- \n" +
                "http://<host>:<port>/v3/api-docs/ \n" +
                "http://<host>:<port>/swagger-ui/index.html \n");
    }
}
